# Configure a default setup of Home Assistant (frontend, api, etc
default_config:
homeassistant:
  customize: !include customize.yaml


  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

#http:
#  ssl_certificate: /config/ssl/fullchain.pem
#  ssl_key: /config/ssl/privkey.pem
#  base_url: https://automation.wilsons.local:8123

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
alert: !include alerts.yaml
switch: !include switches.yaml
shell_command: !include shell_commands.yaml
zone: !include zones.yaml



hassio:
discovery:
  ignore:
    - wink
#    - roku

# Text to speech
tts:
  - platform: google_translate

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_hub_ip

#sensor:
#  - platform: glances
#    host: 127.0.0.1
#    username: !secret glance_user
#    password: !secret glance_pass
#    version: 3
#    resources:
#      - 'processor_load'
#      - 'memory_use_percent'
#      - 'disk_use_percent'


wunderlist:
  client_id: !secret wunder_id
  access_token: !secret wunder_token

#octoprint:
#   host: !secret octo_host
#   api_key: !secret octo_key

#binary_sensor:
#    - platform: octoprint
#      monitored_conditions:
#        - 'Printing'
#        - 'Printing Error'

tplink:
  switch:
   - host: !secret tpswitch1_ip
#   - host: !secret tpswitch2_ip

tuya:
  username: !secret tuya_user
  password: !secret tuya_pass
  country_code: 1

lovelace:
  mode: yaml

zwave:
  usb_path: /dev/ttyUSB0
  device_config: !include zwave_device_config.yaml

zha:
  #usb_path: /dev/ttyAMA0
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

hacs:
  token: !secret github_token

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest
  
notify:
  - name: prowlc
    platform: prowl
    api_key: !secret prowl_key_c
  - name: prowlb
    platform: prowl
    api_key: !secret prowl_key_b
  - name: telegramc
    platform: telegram
    chat_id: !secret telegram_chatid_c

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid_c

roku:
  - host: !secret roku_lr_host
  - host: !secret roku_mb_host
  - host: !secret roku_office_host
  - host: !secret roku_dakota_host
  
mqtt:
  broker: soldier.cloudmqtt.com
  port: !secret mqtt_port
  username: !secret mqtt_ha
  password: !secret mqtt_pass
  
owntracks:
  max_gps_accuracy: 200
  waypoints: true
  mqtt_topic: "owntracks/#"
  events_only: true
  
recorder:
  db_url: !secret sql_info
  
#google:
#   client_id: !secret google_id
#   client_secret: !secret google_secret

#binary_sensor:
 #  - platform: ping
  #   hosts:
   #    guardian: 10.10.10.1
    #   rokulr: 10.10.10.2
     #  rokumb: 10.10.10.3
      # rokuof: 10.10.10.4
      # iosb: 10.10.10.78
      # iosd: 10.10.10.79